# Generated by Django 6.0.7 on 2026-07-25 20:40

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
